version: '3.9'
services:
  proxy:
    image: traefik:2.6.3
    restart: unless-stopped
    command:
      # Dynamic configuration from docker engine
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # HTTP entrypotin and redirection to HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # HTTPS entrypoint
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    depends_on:
      - frama-c-gui-novnc
      - vscode-server

  frama-c-gui:
    image: framac/frama-c-gui:24.0
    restart: unless-stopped
#    command: frama-c-gui -rte -eva src/min_heap.c
#    command: frama-c-gui -rte src/min_heap.c
#    command: frama-c-gui -rte src/min_heap.c
#    command: frama-c-gui -wp-skip-fct realloc src/min_heap.c # does not work, only first level function i suppose?
    command: frama-c-gui -rte -wp-prover altergo,cvc4,z3 -wp-timeout 30 src/min_heap.c
    volumes:
      - ./src:/home/opam/src
    environment:
      - DISPLAY=frama-c-gui-novnc:0.0
    depends_on:
      - frama-c-gui-novnc
  
  frama-c-gui-novnc:
    image: theasp/novnc
    restart: unless-stopped
    environment:
      - RUN_XTERM=no
      - RUN_FLUXBOX=yes
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=900
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frama-c.rule=Host(`frama-c.${DOMAIN:-local}`)"
      - "traefik.http.routers.frama-c.entrypoints=websecure"
      - "traefik.http.routers.frama-c.middlewares=vnc-auto-resize"
      - "traefik.http.middlewares.vnc-auto-resize.redirectregex.regex=^(https://frama-c.${DOMAIN:-local})/?$$"
      - 'traefik.http.middlewares.vnc-auto-resize.redirectregex.replacement=$${1}/vnc.html?resize=scale&autoconnect=1'
  
  vscode-server:
    image: codercom/code-server:4.1.0
    restart: unless-stopped
    volumes:
      - ./src:/home/coder/src
      - ./config/code-server:/home/coder/.config/code-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode.rule=Host(`vscode.${DOMAIN:-local}`)"
      - "traefik.http.routers.vscode.entrypoints=websecure"
